Repository cert-manager/release, pull requests merged in 2020-04, with the labels that each got.

#3 Add support for UBI images and additional architectures
  cmd/cmrel/cmd/gcb_publish.go
  cmd/cmrel/cmd/gcb_stage.go
  pkg/release/consts.go
  pkg/release/unpacker.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/M

#4 Use the 'master' branch for the cmrel tool when launching GCB jobs
  cmd/cmrel/cmd/publish.go
  cmd/cmrel/cmd/stage.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#5 Validate built image name uses is correct/expected
  pkg/release/validation/validate.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#6 Fix image name validation & properly handle UBI image names
  pkg/release/unpacker.go
  pkg/release/validation/validate.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#7 Fix release version used for UBI manifest lists
  cmd/cmrel/cmd/gcb_publish.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#8 Add release tooling for ctl binaries
  cmd/cmrel/cmd/gcb_publish.go
  cmd/cmrel/cmd/gcb_stage.go
  cmd/cmrel/cmd/publish.go
  cmd/cmrel/cmd/stage.go
  pkg/release/binaries/file.go
  pkg/release/consts.go
  pkg/release/unpacker.go
Labels: approved, dco-signoff: yes, lgtm, size/L
