Repository cert-manager/release, pull requests merged in 2021-05, with the labels that each got.

#26 Add darwin/arm64 to list of os/arch for client binaries
  pkg/release/consts.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#24 go 1.13 -> 1.16 + update deps
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, lgtm, size/XL

#30 Revert "Add darwin/arm64 to list of os/arch for client binaries"
  pkg/release/consts.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XS

#28 Publish Helm charts to github.com/jetstack/jetstack-charts
  cmd/cmrel/cmd/gcb_publish.go
  cmd/cmrel/cmd/publish.go
  gcb/publish/cloudbuild.yaml
  gcb/test/helm/README.md
  gcb/test/helm/cloudbuild.yaml
  go.mod
  go.sum
  pkg/release/consts.go
  pkg/release/helm/github_client.go
  pkg/release/helm/helm.go
  pkg/release/helm/helm_test.go
  pkg/release/helm/testdata/README.md
  pkg/release/helm/testdata/cert-manager-v0.1.0-test.1.tgz
  pkg/release/helm/testdata/cert-manager/.helmignore
  pkg/release/helm/testdata/cert-manager/Chart.yaml
  pkg/release/helm/testdata/cert-manager/templates/NOTES.txt
  pkg/release/helm/testdata/cert-manager/templates/_helpers.tpl
  pkg/release/helm/testdata/cert-manager/templates/deployment.yaml
  pkg/release/helm/testdata/cert-manager/templates/hpa.yaml
  pkg/release/helm/testdata/cert-manager/templates/ingress.yaml
  pkg/release/helm/testdata/cert-manager/templates/service.yaml
  pkg/release/helm/testdata/cert-manager/templates/serviceaccount.yaml
  pkg/release/helm/testdata/cert-manager/templates/tests/test-connection.yaml
  pkg/release/helm/testdata/cert-manager/values.yaml
  pkg/release/unpacker.go
Labels: approved, dco-signoff: yes, lgtm, size/XL

#34 Fix nil pointer error / supply a GitHub UsersClient
  cmd/cmrel/cmd/gcb_publish.go
Labels: approved, dco-signoff: yes, lgtm, size/XS
