Repository cert-manager/release, pull requests merged in 2021-09, with the labels that each got.

#44 bump bazel to 4.2.1
  gcb/stage/cloudbuild.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS

#45 Py3 for boilerplate check, control flow docs + trivial tweak to code
  README.md
  cmd/cmrel/cmd/publish.go
  hack/verify_boilerplate.py
Labels: dco-signoff: yes, lgtm, approved, size/S

#47 Get the bazel image from gcr.io/cloud-builders
  gcb/stage/cloudbuild.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS

#48 Add kms/pgp bootstrapping commands for signing
  cmd/cmrel/cmd/bootstrap_pgp.go
  cmd/cmrel/cmd/gcb.go
  cmd/cmrel/cmd/gcb_bootstrap_pgp.go
  cmd/cmrel/cmd/root.go
  gcb/bootstrap-pgp/cloudbuild.yaml
  go.mod
  go.sum
  pkg/sign/internal/kmssigner/kmssigner.go
  pkg/sign/kmspgp.go
Labels: dco-signoff: yes, lgtm, approved, size/XL

#51 Ensure that all keys use a static time
  pkg/sign/kmspgp.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#52 Add script for generating a GPG keyring from an armored key
  hack/helm_keyring.sh
Labels: dco-signoff: yes, lgtm, approved, size/M
