Repository cert-manager/release, pull requests merged in 2022-07, with the labels that each got.

#77 Adds .vscode to .gitignore
  .gitignore
Labels: dco-signoff: yes, lgtm, approved, size/XS

#80 Generate tests
  Makefile
  cmd/cmrel/cmd/generate_prow.go
  cmd/cmrel/cmd/root.go
  go.mod
  go.sum
  pkg/prowgen/configurers.go
  pkg/prowgen/configurers_test.go
  pkg/prowgen/context.go
  pkg/prowgen/generators.go
  pkg/prowgen/globals.go
  pkg/prowgen/types.go
  pkg/prowgen/util.go
  pkg/prowgen/util_test.go
  prowspecs/specs.go
Labels: dco-signoff: yes, size/XXL, lgtm, approved

#81 Bump gcb versions of go to 1.18
  gcb/bootstrap-pgp/cloudbuild.yaml
  gcb/publish/cloudbuild.yaml
  gcb/stage/cloudbuild.yaml
  gcb/test/helm/cloudbuild.yaml
  go.mod
  test/presubmit.sh
Labels: dco-signoff: yes, lgtm, approved, size/M

#82 Changes required post release of 1.9
  prowspecs/specs.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#83 Fix handling of periodic gen with multiple branches
  pkg/prowgen/context.go
Labels: dco-signoff: yes, lgtm, approved, size/S
