Repository cert-manager/release, pull requests merged in 2022-08, with the labels that each got.

#84 Generate tests based on a single branch name
  cmd/cmrel/cmd/generate_prow.go
  pkg/prowgen/context.go
  prowspecs/specs.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#85 Add generator for trivy scan tests
  pkg/prowgen/generators.go
  prowspecs/specs.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#86 Upgrade bazelbuild image
  gcb/makestage/cloudbuild.yaml
  pkg/prowgen/globals.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#87 Upgrade bazelbuild image (fix wrong tag)
  gcb/makestage/cloudbuild.yaml
  pkg/prowgen/globals.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#88 Enable dind for trivy jobs
  pkg/prowgen/generators.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#90 Adds Image to prow context, pass context to job generators.
  pkg/prowgen/context.go
  pkg/prowgen/generators.go
  prowspecs/specs.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#89 Option to write generated prow config, and automatically create pull request against jetstack/testing
  .github/workflows/update-prow-config.yaml
  .github/workflows/verify.yaml
  cmd/cmrel/cmd/generate_prow.go
  prowspecs/specs.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#92 Run git config add safe directory before making changes to testing
  .github/workflows/update-prow-config.yaml
Labels: dco-signoff: yes, lgtm, approved, size/S

#94 Remove create PR workflow
  .github/workflows/generate-prow-tests-specs.yaml
  .github/workflows/update-prow-config.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M

#91 Update CommonImageTest to 20220812-2f64076-4.2.1
  pkg/prowgen/globals.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#95 Upgrade bazelbuild to '20220830-c65cd19-4.2.1'
  pkg/prowgen/globals.go
Labels: dco-signoff: yes, lgtm, approved, size/XS
