Repository cert-manager/release, pull requests merged in 2024-04, with the labels that each got.

#169 Skip shipping cmctl for v1.15.0-alpha.0 and above
  cmd/cmrel/cmd/gcb_publish.go
  cmd/cmrel/cmd/gcb_stage.go
  pkg/release/platforms.go
  pkg/release/platforms_test.go
  pkg/release/unpacker.go
  pkg/release/validation/validate.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#177 Various fixes for cmrel
  gcb/bootstrap-pgp/cloudbuild.yaml
  gcb/publish/cloudbuild.yaml
  gcb/stage/cloudbuild.yaml
  gcb/test/helm/cloudbuild.yaml
  pkg/release/unpacker.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#179 Upload cmctl binaries for releases which need them
  cmd/cmrel/cmd/gcb_publish.go
Labels: dco-signoff: yes, lgtm, approved, size/XS
